name: todolist_riverpod
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter_riverpod: ^2.4.9
  font_awesome_flutter: ^10.6.0
  gap: ^3.0.1
  go_router: ^12.1.3
  google_fonts: ^6.1.0
  intl: ^0.19.0
  path: ^1.8.3
  sqflite: ^2.3.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets\Icon\android\icon_app.png
  min_sdk_android: 21
